### ISSUE TITLE
The possibility to easily add new machine translations

### ISSUE THREAD

**Issue by kerlikur** [buerokratt/Machine-Translation-to-Buerokratt#12]
AS A DevOps
I WANT TO have possibility to easily add new machine translations
SO THAT I can easily add a new machine translation

### Acceptance Criteria:
- [ ] There must be easy way to add new machine translation.
- [ ] Manual to add new machine translation must be created.

**Comment by turnerrainer** [comment]
@kerlikur for me, this one is related to https://github.com/buerokratt/Machine-Translation-to-Buerokratt/issues/5#issuecomment-1282706876

In short - needs more attention to get it done properly.

**Comment by kerlikur** [comment]
@turnerrainer 
This is handled by the machine translation provider,
