### ISSUE TITLE
Feedback of machine translation

### ISSUE THREAD

**Issue by kerlikur** [buerokratt/Machine-Translation-to-Buerokratt#13]
AS AN Analyst
I WANT TO get feedback on machine translations
SO THAT I know the effectiveness of the machine translation

### Acceptance Criteria:
- [ ] If machine translation was used, then ask feedback from the End User in the chat widget when closing the chat.
- [ ] Asking feedback must be in identified language (used machine translation language).
- [ ] Giving feedback must be voluntary and anonymous.
- [ ] The first question should be a yes or no answer. If no continue with the closing steps. If yes continue with the feedback. Questions must be simple.
- [ ] After giving feedback, it is not possible to continue the conversation, only to close the conversation.

**Comment by turnerrainer** [comment]
@kerlikur AC needs to cover the maintenance of these optional feedback questions.

**Comment by kerlikur** [comment]
At the moment there is a general feedback request and does not add separate machine translation feedback.
