### ISSUE TITLE
Machine translation feedback can be found in the analytics module

### ISSUE THREAD

**Issue by kerlikur** [buerokratt/Machine-Translation-to-Buerokratt#25]
AS AN Analyst
I WANT TO see machine translation feedback in the analytics module
SO THAT I can analyze the feedback of the machine translation

### Acceptance Criteria:
- [ ]  Machine translation feedback (#13) can be found in the analytics module.

**Comment by turnerrainer** [comment]
@kerlikur this would be done within another project.

**Comment by kerlikur** [comment]
At the moment there is a general feedback request and does not add separate machine translation feedback.
